version: '3.4'

services:
  snqtranslator.webapi:
    image: "snqtranslatorwebapi"
    container_name: snqtranslator.webapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "32985:80"
      - "443"
    depends_on:
      - dbserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  snqtranslator.aspmvc:
    image: "snqtranslatoraspmvc"
    container_name: snqtranslator.aspmvc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "32990:80"
      - "443"
    depends_on:
      - dbserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  dbserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: "passme!1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "C:\\Share\\Docker\\MSSQL:/var/opt/mssql/data/"